const students = [
  { "id": 1, "name": "Alice", "engagement": "Disengaged", "color": "red" },
  { "id": 2, "name": "Bob", "engagement": "Engaged", "color": "green" },
  { "id": 3, "name": "Charlie", "engagement": "Disengaged", "color": "red" },
  { "id": 4, "name": "David", "engagement": "Engaged", "color": "green" },
  { "id": 5, "name": "Eve", "engagement": "Disengaged", "color": "red" },
  { "id": 6, "name": "Frank", "engagement": "Engaged", "color": "green" },
  { "id": 7, "name": "Grace", "engagement": "Disengaged", "color": "red" },
  { "id": 8, "name": "Hannah", "engagement": "Engaged", "color": "green" },
  { "id": 9, "name": "Ian", "engagement": "Disengaged", "color": "red" },
  { "id": 10, "name": "Jack", "engagement": "Engaged", "color": "green" },
  { "id": 11, "name": "Karen", "engagement": "Disengaged", "color": "red" },
  { "id": 12, "name": "Liam", "engagement": "Engaged", "color": "green" },
  { "id": 13, "name": "Mia", "engagement": "Disengaged", "color": "red" },
  { "id": 14, "name": "Noah", "engagement": "Engaged", "color": "green" },
  { "id": 15, "name": "Olivia", "engagement": "Disengaged", "color": "red" },
  { "id": 16, "name": "Paul", "engagement": "Engaged", "color": "green" },
  { "id": 17, "name": "Quincy", "engagement": "Disengaged", "color": "red" },
  { "id": 18, "name": "Rachel", "engagement": "Engaged", "color": "green" },
  { "id": 19, "name": "Steve", "engagement": "Disengaged", "color": "red" },
  { "id": 20, "name": "Tina", "engagement": "Engaged", "color": "green" },
  { "id": 21, "name": "Uma", "engagement": "Disengaged", "color": "red" },
  { "id": 22, "name": "Victor", "engagement": "Engaged", "color": "green" },
  { "id": 23, "name": "Wendy", "engagement": "Disengaged", "color": "red" },
  { "id": 24, "name": "Xander", "engagement": "Engaged", "color": "green" },
  { "id": 25, "name": "Yara", "engagement": "Disengaged", "color": "red" },
  { "id": 26, "name": "Zane", "engagement": "Engaged", "color": "green" },
  { "id": 27, "name": "Amy", "engagement": "Disengaged", "color": "red" },
  { "id": 28, "name": "Ben", "engagement": "Engaged", "color": "green" },
  { "id": 29, "name": "Cathy", "engagement": "Disengaged", "color": "red" },
  { "id": 30, "name": "Danny", "engagement": "Engaged", "color": "green" }
];

export default students;